# -*- coding: utf-8 -*-
"""Callertask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eOIpROqZmiYkd2E13hpNY7665mPgqrZM
"""

import pandas as pd
import matplotlib.pyplot as plt
data=pd.read_excel("/content/drive/MyDrive/test.xlsx")

data.columns

data.gender

data.list_name

data.status_name

x=data['list_name']
y=data['status_name']

currentgp=data.loc[data['gender']=='F']
x=currentgp['list_name']
y=currentgp['status_name']
plt.xlabel('list_id',fontsize=18)
plt.ylabel('status_name',fontsize=16)
plt.bar(x,y)
plt.show()

#CURRENT USER GROUP FOR DStorm
currentgp=data.loc[data['gender']=='M']
x=currentgp['list_name']
y=currentgp['status_name']
plt.xlabel('list_name',fontsize=18)
plt.ylabel('status_name',fontsize=16)
plt.bar(x,y)
plt.show()