# -*- coding: utf-8 -*-
"""Dialer Task

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18-31wjMNvzrxDrvgjwRSvMvxkfm3FolK
"""

import pandas as pd
from glob import glob

stock_files=sorted(glob('/content/drive/MyDrive/DATA/Dialer_01_*.csv'))
stock_files

pd.concat((pd.read_csv(file).assign(filename=file)
          for file in stock_files),ignore_index=True)

mergedata= pd.concat(pd.read_csv(file).assign(filename=file)
          for file in stock_files)

mergedata

mergedata.to_csv('DATA\Dialermerged.csv')

import pandas as pd
import matplotlib.pyplot as plt
data=pd.read_csv("/content/drive/MyDrive/DATA/DATA_Dialermerged.csv")

x=data['DEAD']
y=data['DC']

#CURRENT USER GROUP FOR DStorm
currentgp=data.loc[data['CURRENT USER GROUP']=='DStorm']
x=currentgp['DEAD']
y=currentgp['DC']
plt.xlabel('DEAD DStorm',fontsize=18)
plt.ylabel('DC DStorm',fontsize=16)
plt.bar(x,y)
plt.show()

#MOST RECENT USER GROUP FOR DStorm
Mostgp=data.loc[data['MOST RECENT USER GROUP']=='DStorm']
x=Mostgp['DEAD']
y=Mostgp['DC']
plt.xlabel('DEAD DStorm',fontsize=18)
plt.ylabel('DC DStorm',fontsize=16)
plt.bar(x,y)
plt.show()

#CURRENT USER GROUP FOR MoonGold
currentgp=data.loc[data['CURRENT USER GROUP']=='MoonGold']
x=currentgp['DEAD']
y=currentgp['DC']
plt.xlabel('DEAD MoonGold',fontsize=18)
plt.ylabel('DC MoonGold',fontsize=16)
plt.bar(x,y)
plt.show()

#MOST RECENT USER GROUP FOR MoonGold
Mostgp=data.loc[data['MOST RECENT USER GROUP']=='MoonGold']
x=Mostgp['DEAD']
y=Mostgp['DC']
plt.xlabel('DEAD MoonGold',fontsize=18)
plt.ylabel('DC MoonGold',fontsize=16)
plt.bar(x,y)
plt.show()

#CURRENT USER GROUP FOR Techative
currentgp=data.loc[data['CURRENT USER GROUP']=='Techative']
x=currentgp['DEAD']
y=currentgp['DC']
plt.xlabel('DEAD Techative',fontsize=18)
plt.ylabel('DC Techative',fontsize=16)
plt.bar(x,y)
plt.show()

#MOST RECENT USER GROUP FOR Techative
Mostgp=data.loc[data['MOST RECENT USER GROUP']=='Techative']
x=Mostgp['DEAD']
y=Mostgp['DC']
plt.xlabel('DEAD Techative',fontsize=18)
plt.ylabel('DC Techative',fontsize=16)
plt.bar(x,y)
plt.show()

#CURRENT USER GROUP FOR JSONS
currentgp=data.loc[data['CURRENT USER GROUP']=='JSONS']
x=currentgp['DEAD']
y=currentgp['DC']
plt.xlabel('DEAD JSONS',fontsize=18)
plt.ylabel('DC JSONS',fontsize=16)
plt.bar(x,y)
plt.show()

#MOST RECENT USER GROUP FOR JSONS
Mostgp=data.loc[data['MOST RECENT USER GROUP']=='JSONS']
x=Mostgp['DEAD']
y=Mostgp['DC']
plt.xlabel('DEAD JSONS',fontsize=18)
plt.ylabel('DC JSONS',fontsize=16)
plt.bar(x,y)
plt.show()

#CURRENT USER GROUP FOR Vibe
currentgp=data.loc[data['CURRENT USER GROUP']=='Vibe']
x=currentgp['DEAD']
y=currentgp['DC']
plt.xlabel('DEAD Vibe',fontsize=18)
plt.ylabel('DC Vibe',fontsize=16)
plt.bar(x,y)
plt.show()

#MOST RECENT USER GROUP FOR Vibe
Mostgp=data.loc[data['MOST RECENT USER GROUP']=='Vibe']
x=Mostgp['DEAD']
y=Mostgp['DC']
plt.xlabel('DEAD Vibe',fontsize=18)
plt.ylabel('DC Vibe',fontsize=16)
plt.bar(x,y)
plt.show()

#CURRENT USER GROUP FOR VIPBlack
currentgp=data.loc[data['CURRENT USER GROUP']=='VIPBlack']
x=currentgp['DEAD']
y=currentgp['DC']
plt.xlabel('DEAD VIPBlack',fontsize=18)
plt.ylabel('DC VIPBlack',fontsize=16)
plt.bar(x,y)
plt.show()

#MOST RECENT USER GROUP FOR VIPBlack
Mostgp=data.loc[data['MOST RECENT USER GROUP']=='VIPBlack']
x=Mostgp['DEAD']
y=Mostgp['DC']
plt.xlabel('DEAD VIPBlack',fontsize=18)
plt.ylabel('DC VIPBlack',fontsize=16)
plt.bar(x,y)
plt.show()

#CURRENT USER GROUP FOR AceGold
currentgp=data.loc[data['CURRENT USER GROUP']=='AceGold']
x=currentgp['DEAD']
y=currentgp['DC']
plt.xlabel('DEAD AceGold',fontsize=18)
plt.ylabel('DC AceGold',fontsize=16)
plt.bar(x,y)
plt.show()

#MOST RECENT USER GROUP FOR AceGold
Mostgp=data.loc[data['MOST RECENT USER GROUP']=='AceGold']
x=Mostgp['DEAD']
y=Mostgp['DC']
plt.xlabel('DEAD AceGold',fontsize=18)
plt.ylabel('DC AceGold',fontsize=16)
plt.bar(x,y)
plt.show()

#CURRENT USER GROUP FOR expertsRedbull
currentgp=data.loc[data['CURRENT USER GROUP']=='expertsRedbull']
x=currentgp['DEAD']
y=currentgp['DC']
plt.xlabel('DEAD expertsRedbull',fontsize=18)
plt.ylabel('DC expertsRedbull',fontsize=16)
plt.bar(x,y)
plt.show()

#MOST RECENT USER GROUP FOR expertsRedbull
Mostgp=data.loc[data['MOST RECENT USER GROUP']=='expertsRedbull']
x=Mostgp['DEAD']
y=Mostgp['DC']
plt.xlabel('DEAD expertsRedbull',fontsize=18)
plt.ylabel('DC expertsRedbull',fontsize=16)
plt.bar(x,y)
plt.show()

#CURRENT USER GROUP FOR FE-Gold
currentgp=data.loc[data['CURRENT USER GROUP']=='FE-Gold']
x=currentgp['DEAD']
y=currentgp['DC']
plt.xlabel('DEAD FE-Gold',fontsize=18)
plt.ylabel('DC FE-Gold',fontsize=16)
plt.bar(x,y)
plt.show()

#MOST RECENT USER GROUP FOR FE-Gold
Mostgp=data.loc[data['MOST RECENT USER GROUP']=='FE-Gold']
x=Mostgp['DEAD']
y=Mostgp['DC']
plt.xlabel('DEAD FE-Gold',fontsize=18)
plt.ylabel('DC FE-Gold',fontsize=16)
plt.bar(x,y)
plt.show()

#CURRENT USER GROUP FOR HSGold
currentgp=data.loc[data['CURRENT USER GROUP']=='HSGold']
x=currentgp['DEAD']
y=currentgp['DC']
plt.xlabel('DEAD HSGold',fontsize=18)
plt.ylabel('DC HSGold',fontsize=16)
plt.bar(x,y)
plt.show()

#MOST RECENT USER GROUP FOR HSGold
Mostgp=data.loc[data['MOST RECENT USER GROUP']=='HSGold']
x=Mostgp['DEAD']
y=Mostgp['DC']
plt.xlabel('DEAD HSGold',fontsize=18)
plt.ylabel('DC HSGold',fontsize=16)
plt.bar(x,y)
plt.show()

#CURRENT USER GROUP FOR HSVibe
currentgp=data.loc[data['CURRENT USER GROUP']=='HSVibe']
x=currentgp['DEAD']
y=currentgp['DC']
plt.xlabel('DEAD HSVibe',fontsize=18)
plt.ylabel('DC HSVibe',fontsize=16)
plt.bar(x,y)
plt.show()

#MOST RECENT USER GROUP FOR HSVibe
Mostgp=data.loc[data['MOST RECENT USER GROUP']=='HSVibe']
x=Mostgp['DEAD']
y=Mostgp['DC']
plt.xlabel('DEAD HSVibe',fontsize=18)
plt.ylabel('DC HSVibe',fontsize=16)
plt.bar(x,y)
plt.show()

#CURRENT USER GROUP FOR KIT
currentgp=data.loc[data['CURRENT USER GROUP']=='KIT']
x=currentgp['DEAD']
y=currentgp['DC']
plt.xlabel('DEAD KIT',fontsize=18)
plt.ylabel('DC KIT',fontsize=16)
plt.bar(x,y)
plt.show()

#CURRENT USER GROUP FOR MIGold
currentgp=data.loc[data['CURRENT USER GROUP']=='MIGold']
x=currentgp['DEAD']
y=currentgp['DC']
plt.xlabel('DEAD MIGold',fontsize=18)
plt.ylabel('DC MIGold',fontsize=16)
plt.bar(x,y)
plt.show()

#CURRENT USER GROUP FOR jsonsGold
currentgp=data.loc[data['CURRENT USER GROUP']=='jsonsGold']
x=currentgp['DEAD']
y=currentgp['DC']
plt.xlabel('DEAD jsonsGold',fontsize=18)
plt.ylabel('DC jsonsGold',fontsize=16)
plt.bar(x,y)
plt.show()

#CURRENT USER GROUP FOR Bravo19V1
currentgp=data.loc[data['CURRENT USER GROUP']=='Bravo19V1']
x=currentgp['DEAD']
y=currentgp['DC']
plt.xlabel('DEAD Bravo19V1',fontsize=18)
plt.ylabel('DC Bravo19V1',fontsize=16)
plt.bar(x,y)
plt.show()

#CURRENT USER GROUP FOR CrossNotchJornaya
currentgp=data.loc[data['CURRENT USER GROUP']=='CrossNotchJornaya']
x=currentgp['DEAD']
y=currentgp['DC']
plt.xlabel('DEAD CrossNotchJornaya',fontsize=18)
plt.ylabel('DC CrossNotchJornaya',fontsize=16)
plt.bar(x,y)
plt.show()

#CURRENT USER GROUP FOR experts
currentgp=data.loc[data['CURRENT USER GROUP']=='experts']
x=currentgp['DEAD']
y=currentgp['DC']
plt.xlabel('DEAD experts',fontsize=18)
plt.ylabel('DC experts',fontsize=16)
plt.bar(x,y)
plt.show()

#CURRENT USER GROUP FOR Avengers
currentgp=data.loc[data['CURRENT USER GROUP']=='Avengers']
x=currentgp['DEAD']
y=currentgp['DC']
plt.xlabel('DEAD Avengers',fontsize=18)
plt.ylabel('DC Avengers',fontsize=16)
plt.bar(x,y)
plt.show()

#MOST RECENT USER GROUP FOR Avengers
Mostgp=data.loc[data['MOST RECENT USER GROUP']=='Avengers']
x=Mostgp['DEAD']
y=Mostgp['DC']
plt.xlabel('DEAD Avengers',fontsize=18)
plt.ylabel('DC Avengers',fontsize=16)
plt.bar(x,y)
plt.show()

#CURRENT USER GROUP FOR rockVIP
currentgp=data.loc[data['CURRENT USER GROUP']=='rockVIP']
x=currentgp['DEAD']
y=currentgp['DC']
plt.xlabel('DEAD rockVIP',fontsize=18)
plt.ylabel('DC rockVIP',fontsize=16)
plt.bar(x,y)
plt.show()

#MOST RECENT USER GROUP FOR rockVIP
Mostgp=data.loc[data['MOST RECENT USER GROUP']=='rockVIP']
x=Mostgp['DEAD']
y=Mostgp['DC']
plt.xlabel('DEAD rockVIP',fontsize=18)
plt.ylabel('DC rockVIP',fontsize=16)
plt.bar(x,y)
plt.show()

#CURRENT USER GROUP FOR RockBPO-2
currentgp=data.loc[data['CURRENT USER GROUP']=='RockBPO-2']
x=currentgp['DEAD']
y=currentgp['DC']
plt.xlabel('DEAD RockBPO-2',fontsize=18)
plt.ylabel('DC RockBPO-2',fontsize=16)
plt.bar(x,y)
plt.show()

#MOST RECENT USER GROUP FOR RockBPO-2
Mostgp=data.loc[data['MOST RECENT USER GROUP']=='RockBPO-2']
x=Mostgp['DEAD']
y=Mostgp['DC']
plt.xlabel('DEAD RockBPO-2',fontsize=18)
plt.ylabel('DC RockBPO-2',fontsize=16)
plt.bar(x,y)
plt.show()

#CURRENT USER GROUP FOR RockmMEDICARE
currentgp=data.loc[data['CURRENT USER GROUP']=='RockmMEDICARE']
x=currentgp['DEAD']
y=currentgp['DC']
plt.xlabel('DEAD RockmMEDICARE',fontsize=18)
plt.ylabel('DC RockmMEDICARE',fontsize=16)
plt.bar(x,y)
plt.show()

#MOST RECENT USER GROUP FOR RockmMEDICARE
Mostgp=data.loc[data['MOST RECENT USER GROUP']=='RockmMEDICARE']
x=Mostgp['DEAD']
y=Mostgp['DC']
plt.xlabel('DEAD RockmMEDICARE',fontsize=18)
plt.ylabel('DC RockmMEDICARE',fontsize=16)
plt.bar(x,y)
plt.show()